
import type { Airport } from './types';

export const AIRPORTS: Airport[] = [
  { code: 'JFK', name: 'John F. Kennedy International Airport', city: 'New York', country: 'USA', arabicName: 'نيويورك', arabicCountry: 'الولايات المتحدة', useCount: 10 },
  { code: 'LAX', name: 'Los Angeles International Airport', city: 'Los Angeles', country: 'USA', arabicName: 'لوس أنجلوس', arabicCountry: 'الولايات المتحدة', useCount: 5 },
  { code: 'LHR', name: 'Heathrow Airport', city: 'London', country: 'United Kingdom', arabicName: 'لندن', arabicCountry: 'المملكة المتحدة', useCount: 15 },
  { code: 'CDG', name: 'Charles de Gaulle Airport', city: 'Paris', country: 'France', arabicName: 'باريس', arabicCountry: 'فرنسا', useCount: 8 },
  { code: 'HND', name: 'Haneda Airport', city: 'Tokyo', country: 'Japan', arabicName: 'طوكيو', arabicCountry: 'اليابان' },
  { code: 'DXB', name: 'Dubai International Airport', city: 'Dubai', country: 'UAE', arabicName: 'دبي', arabicCountry: 'الإمارات', useCount: 30 },
  { code: 'AMS', name: 'Amsterdam Airport Schiphol', city: 'Amsterdam', country: 'Netherlands', arabicName: 'أمستردام', arabicCountry: 'هولندا' },
  { code: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt', country: 'Germany', arabicName: 'فرانكفورت', arabicCountry: 'ألمانيا' },
  { code: 'IST', name: 'Istanbul Airport', city: 'Istanbul', country: 'Turkey', arabicName: 'اسطنبول', arabicCountry: 'تركيا', useCount: 25 },
  { code: 'SAW', name: 'Sabiha Gokcen International Airport', city: 'Istanbul', country: 'Turkey', arabicName: 'اسطنبول - صبيحة', arabicCountry: 'تركيا', useCount: 20 },
  { code: 'ESB', name: 'Esenboğa International Airport', city: 'Ankara', country: 'Turkey', arabicName: 'أنقرة', arabicCountry: 'تركيا' },
  { code: 'BGW', name: 'Baghdad International Airport', city: 'Baghdad', country: 'Iraq', arabicName: 'بغداد', arabicCountry: 'العراق', useCount: 50 },
  { code: 'NJF', name: 'Al Najaf International Airport', city: 'Najaf', country: 'Iraq', arabicName: 'النجف', arabicCountry: 'العراق', useCount: 45 },
  { code: 'EBL', name: 'Erbil International Airport', city: 'Erbil', country: 'Iraq', arabicName: 'أربيل', arabicCountry: 'العراق', useCount: 20 },
  { code: 'BSR', name: 'Basra International Airport', city: 'Basra', country: 'Iraq', arabicName: 'البصرة', arabicCountry: 'العراق', useCount: 18 },
  { code: 'ISU', name: 'Sulaimaniyah International Airport', city: 'Sulaimaniyah', country: 'Iraq', arabicName: 'السليمانية', arabicCountry: 'العراق', useCount: 15 },
  { code: 'CAI', name: 'Cairo International Airport', city: 'Cairo', country: 'Egypt', arabicName: 'القاهرة', arabicCountry: 'مصر', useCount: 12 },
  { code: 'BEY', name: 'Beirut-Rafic Hariri International Airport', city: 'Beirut', country: 'Lebanon', arabicName: 'بيروت', arabicCountry: 'لبنان', useCount: 18 },
  { code: 'AMM', name: 'Queen Alia International Airport', city: 'Amman', country: 'Jordan', arabicName: 'عمان', arabicCountry: 'الأردن', useCount: 9 },
  { code: 'RUH', name: 'King Khalid International Airport', city: 'Riyadh', country: 'Saudi Arabia', arabicName: 'الرياض', arabicCountry: 'السعودية' },
  { code: 'JED', name: 'King Abdulaziz International Airport', city: 'Jeddah', country: 'Saudi Arabia', arabicName: 'جدة', arabicCountry: 'السعودية' },
  { code: 'KWI', name: 'Kuwait International Airport', city: 'Kuwait City', country: 'Kuwait', arabicName: 'الكويت', arabicCountry: 'الكويت' },
  { code: 'DOH', name: 'Hamad International Airport', city: 'Doha', country: 'Qatar', arabicName: 'الدوحة', arabicCountry: 'قطر' },
  { code: 'DAM', name: 'Damascus International Airport', city: 'Damascus', country: 'Syria', arabicName: 'دمشق', arabicCountry: 'سوريا' },
  { code: 'ALP', name: 'Aleppo International Airport', city: 'Aleppo', country: 'Syria', arabicName: 'حلب', arabicCountry: 'سوريا' },
  { code: 'THR', name: 'Mehrabad International Airport', city: 'Tehran', country: 'Iran', arabicName: 'طهران', arabicCountry: 'إيران', useCount: 22 },
  { code: 'IKA', name: 'Imam Khomeini International Airport', city: 'Tehran', country: 'Iran', arabicName: 'طهران - الإمام الخميني', arabicCountry: 'إيران', useCount: 19 },
  { code: 'MHD', name: 'Mashhad International Airport', city: 'Mashhad', country: 'Iran', arabicName: 'مشهد', arabicCountry: 'إيران', useCount: 16 },
  { code: 'SYZ', name: 'Shiraz International Airport', city: 'Shiraz', country: 'Iran', arabicName: 'شيراز', arabicCountry: 'إيران' },
  { code: 'KUL', name: 'Kuala Lumpur International Airport', city: 'Kuala Lumpur', country: 'Malaysia', arabicName: 'كوالالمبور', arabicCountry: 'ماليزيا' },
  { code: 'BKK', name: 'Suvarnabhumi Airport', city: 'Bangkok', country: 'Thailand', arabicName: 'بانكوك', arabicCountry: 'تايلاند' },
  { code: 'SIN', name: 'Singapore Changi Airport', city: 'Singapore', country: 'Singapore', arabicName: 'سنغافورة', arabicCountry: 'سنغافورة' },
  { code: 'DEL', name: 'Indira Gandhi International Airport', city: 'Delhi', country: 'India', arabicName: 'دلهي', arabicCountry: 'الهند' },
  { code: 'BOM', name: 'Chhatrapati Shivaji Maharaj International Airport', city: 'Mumbai', country: 'India', arabicName: 'مومباي', arabicCountry: 'الهند' },
  { code: 'AUH', name: 'Abu Dhabi International Airport', city: 'Abu Dhabi', country: 'UAE', arabicName: 'أبو ظبي', arabicCountry: 'الإمارات' },
  { code: 'SHJ', name: 'Sharjah International Airport', city: 'Sharjah', country: 'UAE', arabicName: 'الشارقة', arabicCountry: 'الإمارات' },
  { code: 'MCT', name: 'Muscat International Airport', city: 'Muscat', country: 'Oman', arabicName: 'مسقط', arabicCountry: 'عمان' },
  { code: 'BAH', name: 'Bahrain International Airport', city: 'Manama', country: 'Bahrain', arabicName: 'البحرين', arabicCountry: 'البحرين' },
  { code: 'PEK', name: 'Beijing Capital International Airport', city: 'Beijing', country: 'China', arabicName: 'بكين', arabicCountry: 'الصين' },
  { code: 'PVG', name: 'Shanghai Pudong International Airport', city: 'Shanghai', country: 'China', arabicName: 'شنغهاي', arabicCountry: 'الصين' },
  { code: 'CAN', name: 'Guangzhou Baiyun International Airport', city: 'Guangzhou', country: 'China', arabicName: 'قوانغتشو', arabicCountry: 'الصين' },
  { code: 'SYD', name: 'Sydney Kingsford Smith Airport', city: 'Sydney', country: 'Australia', arabicName: 'سيدني', arabicCountry: 'أستراليا' },
  { code: 'MEL', name: 'Melbourne Airport', city: 'Melbourne', country: 'Australia', arabicName: 'ملبورن', arabicCountry: 'أستراليا' },
  { code: 'YYZ', name: 'Toronto Pearson International Airport', city: 'Toronto', country: 'Canada', arabicName: 'تورونتو', arabicCountry: 'كندا' },
  { code: 'YVR', name: 'Vancouver International Airport', city: 'Vancouver', country: 'Canada', arabicName: 'فانكوفر', arabicCountry: 'كندا' },
  { code: 'GRU', name: 'São Paulo/Guarulhos International Airport', city: 'São Paulo', country: 'Brazil', arabicName: 'ساو باولو', arabicCountry: 'البرازيل' },
  { code: 'MEX', name: 'Mexico City International Airport', city: 'Mexico City', country: 'Mexico', arabicName: 'مكسيكو سيتي', arabicCountry: 'المكسيك' },
  { code: 'SVO', name: 'Sheremetyevo International Airport', city: 'Moscow', country: 'Russia', arabicName: 'موسكو - شيريميتييفو', arabicCountry: 'روسيا' },
  { code: 'DME', name: 'Domodedovo International Airport', city: 'Moscow', country: 'Russia', arabicName: 'موسكو - دوموديدوفو', arabicCountry: 'روسيا' },
  { code: 'BCN', name: 'Barcelona–El Prat Airport', city: 'Barcelona', country: 'Spain', arabicName: 'برشلونة', arabicCountry: 'إسبانيا' },
  { code: 'MAD', name: 'Adolfo Suárez Madrid–Barajas Airport', city: 'Madrid', country: 'Spain', arabicName: 'مدريد', arabicCountry: 'إسبانيا' },
  { code: 'FCO', name: 'Leonardo da Vinci–Fiumicino Airport', city: 'Rome', country: 'Italy', arabicName: 'روما', arabicCountry: 'إيطاليا' },
  { code: 'MXP', name: 'Milan Malpensa Airport', city: 'Milan', country: 'Italy', arabicName: 'ميلانو', arabicCountry: 'إيطاليا' },
  { code: 'ATH', name: 'Athens International Airport', city: 'Athens', country: 'Greece', arabicName: 'أثينا', arabicCountry: 'اليونان' },
  { code: 'LIS', name: 'Lisbon Airport', city: 'Lisbon', country: 'Portugal', arabicName: 'لشبونة', arabicCountry: 'البرتغال' },
  { code: 'CPH', name: 'Copenhagen Airport', city: 'Copenhagen', country: 'Denmark', arabicName: 'كوبنهاغن', arabicCountry: 'الدنمارك' },
  { code: 'OSL', name: 'Oslo Airport, Gardermoen', city: 'Oslo', country: 'Norway', arabicName: 'أوسلو', arabicCountry: 'النرويج' },
  { code: 'ARN', name: 'Stockholm Arlanda Airport', city: 'Stockholm', country: 'Sweden', arabicName: 'ستوكهولم', arabicCountry: 'السويد' },
  { code: 'HEL', name: 'Helsinki-Vantaa Airport', city: 'Helsinki', country: 'Finland', arabicName: 'هلسنكي', arabicCountry: 'فنلندا' },
  { code: 'VIE', name: 'Vienna International Airport', city: 'Vienna', country: 'Austria', arabicName: 'فيينا', arabicCountry: 'النمسا' },
  { code: 'ZRH', name: 'Zurich Airport', city: 'Zurich', country: 'Switzerland', arabicName: 'زيورخ', arabicCountry: 'سويسرا' },
  { code: 'GVA', name: 'Geneva Airport', city: 'Geneva', country: 'Switzerland', arabicName: 'جنيف', arabicCountry: 'سويسرا' },
  { code: 'BRU', name: 'Brussels Airport', city: 'Brussels', country: 'Belgium', arabicName: 'بروكسل', arabicCountry: 'بلجيكا' },
  { code: 'DUB', name: 'Dublin Airport', city: 'Dublin', country: 'Ireland', arabicName: 'دبلن', arabicCountry: 'أيرلندا' },
  { code: 'PRG', name: 'Václav Havel Airport Prague', city: 'Prague', country: 'Czech Republic', arabicName: 'براغ', arabicCountry: 'جمهورية التشيك' },
  { code: 'BUD', name: 'Budapest Ferenc Liszt International Airport', city: 'Budapest', country: 'Hungary', arabicName: 'بودابست', arabicCountry: 'المجر' },
  { code: 'WAW', name: 'Warsaw Chopin Airport', city: 'Warsaw', country: 'Poland', arabicName: 'وارسو', arabicCountry: 'بولندا' },
  { code: 'KBP', name: 'Boryspil International Airport', city: 'Kyiv', country: 'Ukraine', arabicName: 'كييف', arabicCountry: 'أوكرانيا' },
  { code: 'OTP', name: 'Henri Coandă International Airport', city: 'Bucharest', country: 'Romania', arabicName: 'بوخارست', arabicCountry: 'رومانيا' },
];
