
import {
  LayoutDashboard,
  Users,
  Briefcase,
  Plane,
  CircleDollarSign,
  FileText,
  Settings,
  ShieldCheck,
  MessageSquare,
  Bell,
  CreditCard,
  Building,
  ArrowLeftRight,
  UserPlus,
  Ticket,
  Layers,
  PieChart,
  BookUser,
  Landmark,
  HandCoins,
  Wallet,
  ReceiptText,
  Container,
  Mail,
  Bot,
  FileCheck2,
  FileTerminal,
  FileX2,
  UserCog,
  Palette,
  PenSquare,
  FileCog as FileCogIcon,
  Sparkles,
  UserRoundCog,
  UserRoundSearch,
  FileSliders,
  Printer,
  Presentation,
  LayoutList,
  FolderGit2,
  Scale,
  PiggyBank,
  GanttChartSquare,
  AreaChart,
  Contact,
  Store,
  FileDown,
  GitBranch,
  FileUp,
  Banknote,
  ChevronsRightLeft,
  Boxes,
  Repeat,
  History,
  Wand2,
  Activity,
  Waypoints,
  NotebookText,
  BarChart3,
  Users2,
  Network,
  Calculator,
} from "lucide-react";

export const navConfig = {
  mainNav: [
    {
      title: "الرئيسية",
      href: "/dashboard",
      icon: LayoutDashboard,
    },
  ],
  relations: {
    title: "العلاقات",
    icon: Contact,
    items: [
      {
        title: "العملاء والموردين",
        href: "/clients",
        icon: Users2,
      },
      {
        title: "الحملات",
        href: "/campaigns",
        icon: MessageSquare,
      },
    ],
  },
  operations: {
    title: "العمليات المحاسبية",
    icon: Calculator,
    items: [
      {
        title: "حجوزات الطيران",
        href: "/bookings",
        icon: Plane,
      },
      {
        title: "طلبات الفيزا",
        href: "/visas",
        icon: CreditCard,
      },
       {
        title: "الاشتراكات",
        href: "/subscriptions",
        icon: Repeat,
      },
       {
        title: "الحوالات",
        href: "/accounts/remittances",
        icon: ArrowLeftRight,
      },
    ],
  },
  vouchers: {
    title: "السندات",
    icon: FileText,
    items: [
       {
        title: "سجل السندات",
        href: "/accounts/vouchers/list",
        icon: ReceiptText,
      },
    ],
  },
  accounting: {
    title: "المحاسبة",
    icon: Wallet,
    items: [
       {
        title: "الصناديق",
        href: "/boxes",
        icon: Wallet,
      },
      {
        title: "البورصات",
        href: "/exchanges",
        icon: Waypoints,
      },
    ],
  },
  customBusiness: {
    title: "الأعمال المخصصة",
    icon: Briefcase,
    items: [
        {
            title: "السكمنت",
            href: "/segments",
            icon: Layers,
        },
        {
            title: "توزيع الحصص",
            href: "/profit-sharing",
            icon: PiggyBank,
        }
    ]
  },
  reports: {
    title: "التقارير والأدوات",
    icon: BarChart3,
    items: [
      { title: "تقرير الأرصدة", href: "/reports/debts", icon: BookUser },
      { title: "كشف حساب", href: "/reports/account-statement", icon: NotebookText },
      { title: "تحليل الرحلات", href: "/reports/flight-analysis", icon: Plane },
      { title: "الأرباح والخسائر", href: "/reports/profit-loss", icon: GanttChartSquare, },
      { title: "تحليل الربحية", href: "/reports/profitability-analysis", icon: PieChart },
      { title: "التدفق النقدي", href: "/reports/cash-flow", icon: Waypoints },
      { title: "التدقيق الذكي", href: "/reconciliation", icon: Wand2 },
    ],
  },
  system: {
    title: "النظام",
    icon: Network,
    items: [
      { title: "الإعدادات العامة", href: "/settings", icon: Settings },
      { title: "الموظفين والصلاحيات", href: "/users", icon: UserCog },
      { title: "الأدوات المالية", href: "/finance-tools", icon: Landmark },
      { title: "قوالب الرسائل", href: "/templates", icon: PenSquare },
      { title: "سجل النشاطات", href: "/system/activity-log", icon: FileTerminal },
      { title: "سجل الأخطاء", href: "/system/error-log", icon: FileCogIcon },
      { title: "تدقيق البيانات", href: "/system/data-audit", icon: FileCheck2 },
      { title: "سجل المحذوفات", href: "/system/deleted-log", icon: FileX2 },
    ],
  },
};
